[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.version_machine]

    [tool.version_machine.__version__]
    path = "version_machine/__version__.py"
    increment = "patch"
